version: '3.8'

services:
  # service name
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - frontend
    restart: always
    networks:
      - net

  backend:
    image: bjnandi/ci-cd-mern-dc-backend:v1.0.${IMAGE_TAG}
    # container_name: backend

    env_file: ./.env
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb
    restart: always
    networks:
      - net

  frontend:
    image: bjnandi/ci-cd-mern-dc-frontend:v1.0.${IMAGE_TAG}
    # container_name: frontend

    depends_on:
      - backend
    restart: always
    networks:
      - net

  # Database service
  mongodb:
    image: mongo:latest
    # container_name: mongodb

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    volumes:
      - ./../mydata:/data/db

    networks:
      - net

# Volumes define
volumes: 
  mydata:

networks:
  net:
    external: true